import "@/react-ui-library/styles.css";
import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "next-themes";
import { Bounce } from "react-toastify";

import AppSidebar from "@/app/[locale]/AppSidebar";
import { routing } from "@/i18n/routing";
import SearchInput from "@/react-ui-library/components/inputs/search-input/SearchInput";
import { Toaster } from "@/react-ui-library/components/toasts/Toaster";
import Topbar from "@/react-ui-library/components/topbar/Topbar";

import AppTopbar from "./AppTopbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <NextIntlClientProvider>
          <ThemeProvider>
            <div className="body-wrapper">
              <AppTopbar />
              <div className="page-wrapper">
                <AppSidebar />
                <div className="page-content">{children}</div>
                <Toaster />
              </div>
            </div>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
